### ISSUE TITLE
how to download datasets

### ISSUE THREAD

**Issue by AndrewTal** [uta-smile/DeepAttnMISL_MEDIA#1]
Is there a data link available for download? 
I found the mailbox on the MCO website and sent a data request, but there is no reply.
I went to the NLST website and found that pathological images can only be delivered via hard drive.
Is there any way to get data more easily? Thanks!

**Comment by utayao** [comment]
Unfortunately, I don't think there have eaiser ways to get MCO and NLST dataset. But you could download TCGA dataset online.
